drop type if exists app_public.space_item;
drop type if exists app_public.submittable_entity;
drop type if exists app_public.revisioned_submittable_entity;
drop table if exists app_public.messages cascade;
drop table if exists app_public.message_revisions cascade;
drop table if exists app_public.topic_revisions cascade;
drop table if exists app_public.space_postings cascade;
drop table if exists app_public.space_submissions cascade;
drop table if exists app_public.space_subscriptions cascade;
drop table if exists app_public.spaces cascade;
drop type if exists app_public.space_role cascade;
drop type if exists app_public.space_capability cascade;
drop type if exists app_public.itc_stamp;