drop function app_public.space_filings_item_created_at(filing app_public.space_filings);
drop function app_public.space_filings_item_updated_at(filing app_public.space_filings);
drop function app_public.space_filings_item_name(filing app_public.space_filings);
drop type if exists app_public.space_item;
drop table if exists app_public.space_items;
drop table if exists app_public.space_inputs;
drop table if exists app_public.space_postings;
drop table if exists app_public.space_filings;
drop table if exists app_public.spaces;
drop type if exists app_public.itc_stamp;